name: EC2 Cleanup Workflow

on:
  workflow_dispatch:
    inputs:
      region:
        description: "AWS Region"
        required: false
        default: "eu-west-1"
      access_key_id:
        description: "AWS Access Key ID"
        required: true
      secret_access_key:
        description: "AWS Secret Access Key"
        required: true
      session_token:
        description: "AWS Session Token (optional)"
        required: false
      action:
        description: "Choose action: analyze | dryrun_delete | delete"
        required: true
        default: "analyze"

jobs:
  ec2_cleanup:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ github.event.inputs.access_key_id }}
      AWS_SECRET_ACCESS_KEY: ${{ github.event.inputs.secret_access_key }}
      AWS_SESSION_TOKEN: ${{ github.event.inputs.session_token }}
      REGION: ${{ github.event.inputs.region }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install boto3

      - name: List repo structure (for debug)
        run: ls -R

      - name: Run the selected action
        run: |
          echo "Running action: ${{ github.event.inputs.action }}"

          case "${{ github.event.inputs.action }}" in
            analyze)
              python scripts/analyze.py --region "${{ env.REGION }}"
              ;;
            dryrun_delete)
              python scripts/dryrun_delete.py --region "${{ env.REGION }}"
              ;;
            delete)
              python scripts/delete.py --region "${{ env.REGION }}"
              ;;
            *)
              echo "❌ Invalid action: ${{ github.event.inputs.action }}"
              exit 1
              ;;
          esac
