name: EC2 Cleanup Workflow

on:
  workflow_dispatch:
    inputs:
      region:
        description: "AWS Region"
        required: false
        default: "eu-west-1"
      action:
        description: "Choose action: analyze | dryrun_delete | delete"
        required: true
        default: "analyze"
      access_key_id:
        description: "AWS Access Key ID"
        required: true
      secret_access_key:
        description: "AWS Secret Access Key"
        required: true
      session_token:
        description: "AWS Session Token (optional)"
        required: false

jobs:
  ec2-cleanup:
    runs-on: ubuntu-latest
    name: EC2 Cleanup Operation

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main  # Ensure we’re on the GitHub Pages branch
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install boto3

      - name: Run cleanup script and generate results.html
        env:
          AWS_ACCESS_KEY_ID: ${{ github.event.inputs.access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ github.event.inputs.secret_access_key }}
          AWS_SESSION_TOKEN: ${{ github.event.inputs.session_token }}
        run: |
          mkdir -p output
          case "${{ github.event.inputs.action }}" in
            analyze)
              python scripts/analyze.py --region "${{ github.event.inputs.region }}" > output/results.html
              ;;
            dryrun_delete)
              python scripts/dryrun_delete.py --region "${{ github.event.inputs.region }}" > output/results.html
              ;;
            delete)
              python scripts/delete.py --region "${{ github.event.inputs.region }}" > output/results.html
              ;;
            *)
              echo "Invalid action input" > output/results.html
              ;;
          esac

      - name: Push results.html to main branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Use token-authenticated remote
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}

          cp output/results.html ./docs/output.html
          git add docs/output.html
          git commit -m "🚀 Auto-update results.html from cleanup run" || echo "No changes to commit"
          git push origin HEAD:main

