name: EC2 Volume Cleanup

on:
  workflow_dispatch:
    inputs:
      region:
        description: "AWS Region"
        required: true
        default: "eu-west-1"
      access_key_id:
        description: "AWS Access Key ID"
        required: true
      secret_access_key:
        description: "AWS Secret Access Key"
        required: true
      session_token:
        description: "AWS Session Token"
        required: false
      confirm_delete:
        description: "Confirm Deletion"
        required: true
        default: "false"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install boto3

      - name: Run cleanup script
        env:
          AWS_ACCESS_KEY_ID: ${{ github.event.inputs.access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ github.event.inputs.secret_access_key }}
          AWS_SESSION_TOKEN: ${{ github.event.inputs.session_token }}
        run: |
          python api/ec2_volume_cleanup.py \
            --region "${{ github.event.inputs.region }}" \
            ${{ github.event.inputs.confirm_delete == 'true' && '--yes' || '' }}
