name: EC2 Cleanup Workflow

on:
  workflow_dispatch:
    inputs:
      region:
        description: "AWS Region"
        required: false
        default: "eu-west-1"
      access_key_id:
        description: "AWS Access Key ID"
        required: true
      secret_access_key:
        description: "AWS Secret Access Key"
        required: true
      session_token:
        description: "AWS Session Token"
        required: false
      action:
        description: "Choose operation: analyze, dryrun, delete"
        required: true
        default: "analyze"

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install boto3

      - name: Run selected cleanup action
        env:
          AWS_ACCESS_KEY_ID: ${{ github.event.inputs.access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ github.event.inputs.secret_access_key }}
          AWS_SESSION_TOKEN: ${{ github.event.inputs.session_token }}
        run: |
          case "${{ github.event.inputs.action }}" in
            analyze)
              echo "Running analysis..."
              python analyze.py --region "${{ github.event.inputs.region }}"
              ;;
            dryrun)
              echo "Running dry-run deletion..."
              python dryrun_delete.py --region "${{ github.event.inputs.region }}"
              ;;
            delete)
              echo "Running actual deletion..."
              python delete.py --region "${{ github.event.inputs.region }}"
              ;;
            *)
              echo "❌ Invalid action selected: '${{ github.event.inputs.action }}'"
              exit 1
              ;;
          esac
