name: EC2 Cleanup Workflow

on:
  workflow_dispatch:
    inputs:
      region:
        description: "AWS Region"
        required: false
        default: "eu-west-1"
      action:
        description: "Choose action: analyze | dryrun_delete | delete"
        required: true
        default: "analyze"
      access_key_id:
        description: "AWS Access Key ID"
        required: true
      secret_access_key:
        description: "AWS Secret Access Key"
        required: true
      session_token:
        description: "AWS Session Token (optional)"
        required: false

jobs:
  ec2-cleanup:
    runs-on: ubuntu-latest
    name: EC2 Cleanup Operation

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install boto3

      - name: Create output directory
        run: mkdir -p output

      - name: Run cleanup script based on action
        env:
          AWS_ACCESS_KEY_ID: ${{ github.event.inputs.access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ github.event.inputs.secret_access_key }}
          AWS_SESSION_TOKEN: ${{ github.event.inputs.session_token }}
        run: |
          case "${{ github.event.inputs.action }}" in
            analyze)
              python scripts/analyze.py --region "${{ github.event.inputs.region }}"
              ;;
            dryrun_delete)
              python scripts/dryrun_delete.py --region "${{ github.event.inputs.region }}"
              ;;
            delete)
              python scripts/delete.py --region "${{ github.event.inputs.region }}"
              ;;
            *)
              echo "Invalid action input"; exit 1;
              ;;
          esac

      - name: Upload cleanup results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cleanup-results
          path: output/

  deploy-results:
    name: Deploy Results to GitHub Pages
    needs: ec2-cleanup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          persist-credentials: true

      - name: Download artifact from cleanup job
        uses: actions/download-artifact@v4
        with:
          name: cleanup-results
          path: ./output

      - name: Copy results.html to root of gh-pages
        run: |
          if [ -f ./output/results.html ]; then
            cp ./output/results.html ./results.html
          else
            echo "results.html not found in output/"
            exit 1
          fi

      - name: Commit and push results.html to gh-pages
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add results.html
          git commit -m "🔄 Update results.html from latest cleanup"
          git push origin gh-pages
